reviewers:
  # The default reviewers
  defaults:
    - repository-owners
groups:
    repository-owners:
    - WilloIzCitron
    - unjown
    
files:
  # Keys are glob expressions.
  # You can assign groups defined above as well as GitHub usernames.
  '**':
    - repository-owners # group
